name:                PD
version:             1.0
github:              ""
license:             BSD-3-Clause
author:              "Alejandro Fernández Trigo"
maintainer:          "alefertri1@alum.us.es"
copyright:           "2023 Alejandro Fernández Trigo"

extra-source-files:
- README.md

description:         Please see the README.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  PD-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PD
